# Generated by Django 6.0.7 on 2026-07-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderhistory',
            options={'verbose_name_plural': 'Order Histories'},
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('p', 'Preparing'), ('r', 'Ready'), ('s', 'Served')], default='p', max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('ps', 'Partially Ready'), ('s', 'Served'), ('b', 'Billed')], default='p', max_length=2),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('ps', 'Partially Ready'), ('s', 'Served'), ('b', 'Billed')]),
        ),
    ]
