# Generated by Django 6.0.7 on 2026-07-15 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_orderhistory_options_orderitem_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KITCHEN_STATION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='menuitem',
            name='default_priority',
            field=models.CharField(choices=[('3', 'High'), ('2', 'Medium'), ('1', 'Low')], default='2', max_length=2),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='est_time',
            field=models.PositiveIntegerField(help_text='Write estimated preparation time in minutes', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='priority',
            field=models.CharField(choices=[('3', 'High'), ('2', 'Medium'), ('1', 'Low')], default='2', max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('ps', 'Partially Served'), ('s', 'Served'), ('b', 'Billed')], default='p', max_length=2),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('ps', 'Partially Served'), ('s', 'Served'), ('b', 'Billed')]),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.kitchen_station'),
        ),
    ]
