# Generated by Django 6.0.7 on 2026-07-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_kitchen_station_menuitem_default_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='est_time',
            field=models.PositiveIntegerField(blank=True, help_text='Write estimated preparation time in minutes', null=True),
        ),
    ]
