# Generated by Django 6.0.7 on 2026-07-15 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_menuitem_est_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KITCHEN_STATION',
            new_name='KitchenStation',
        ),
    ]
