# Generated by Django 6.0.7 on 2026-07-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_rename_kitchen_station_kitchenstation'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchenstation',
            name='code',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
