# Generated by Django 6.0.7 on 2026-07-15 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_kitchenstation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='orders.kitchenstation'),
        ),
    ]
